"""
PDF report generation for a case (reportlab).
Falls back gracefully if reportlab is unavailable.
"""
import io
import time

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                    TableStyle)
    _HAS = True
except Exception:
    _HAS = False

# palette echoing the console
INK = colors.HexColor("#0A0E17")
ACCENT = colors.HexColor("#1E90B5")
LINE = colors.HexColor("#CBD5E1")
MUT = colors.HexColor("#64748B")
SEV = {"critical": colors.HexColor("#E5484D"), "medium": colors.HexColor("#E8883C"),
       "low": colors.HexColor("#E0B341"), "info": colors.HexColor("#3DBE6B")}


def case_pdf(case: dict) -> bytes:
    if not _HAS:
        raise RuntimeError("reportlab not installed")
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=22 * mm, bottomMargin=18 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm,
                            title=f"Sentinel report — {case['id']}")
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=INK, fontSize=22, spaceAfter=2)
    sub = ParagraphStyle("sub", parent=ss["Normal"], textColor=MUT, fontSize=9, spaceAfter=14)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=ACCENT, fontSize=12, spaceBefore=10)
    body = ParagraphStyle("body", parent=ss["Normal"], fontSize=9.5, leading=14)
    small = ParagraphStyle("small", parent=ss["Normal"], fontSize=8, textColor=MUT)

    findings = case.get("findings", [])
    sev_counts = {}
    for f in findings:
        sev_counts[f["severity"]] = sev_counts.get(f["severity"], 0) + 1

    story = []
    story.append(Paragraph("SENTINEL OSINT — Investigation Report", h1))
    story.append(Paragraph(
        f"Case <b>{case['name']}</b> &nbsp;·&nbsp; {case['id']} &nbsp;·&nbsp; "
        f"target {case.get('target') or '—'} &nbsp;·&nbsp; status {case['status']} "
        f"&nbsp;·&nbsp; generated {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}", sub))

    # summary tiles
    summary = [["Findings", "Critical", "Medium", "Low / Info"],
               [str(len(findings)), str(sev_counts.get("critical", 0)),
                str(sev_counts.get("medium", 0)),
                str(sev_counts.get("low", 0) + sev_counts.get("info", 0))]]
    t = Table(summary, colWidths=[43 * mm] * 4)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("TEXTCOLOR", (0, 0), (-1, 0), MUT),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, 1), 18),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("TEXTCOLOR", (1, 1), (1, 1), SEV["critical"]),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(t)

    if case.get("notes"):
        story.append(Paragraph("Case notes", h2))
        story.append(Paragraph(case["notes"], body))

    story.append(Paragraph("Findings", h2))
    if findings:
        data = [["Module", "Selector", "Summary", "Severity"]]
        for f in findings:
            data.append([f["module"], f["selector"][:40], (f.get("summary") or "")[:46],
                         f["severity"]])
        ft = Table(data, colWidths=[26 * mm, 48 * mm, 68 * mm, 24 * mm], repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), INK),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, LINE),
            ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
        for i, f in enumerate(findings, start=1):
            style.append(("TEXTCOLOR", (3, i), (3, i), SEV.get(f["severity"], MUT)))
            style.append(("FONTNAME", (3, i), (3, i), "Helvetica-Bold"))
        ft.setStyle(TableStyle(style))
        story.append(ft)
    else:
        story.append(Paragraph("No findings logged for this case.", body))

    story.append(Spacer(1, 16))
    story.append(Paragraph("Generated by Sentinel OSINT · authorized use only.", small))

    doc.build(story)
    return buf.getvalue()
